language: R
sudo: false
cran: http://cran.rstudio.com
cache: packages
warnings_are_errors: true
os:
  - linux
  - osx

r_build_args: "--no-manual --no-build-vignettes"
r_check_args: "--as-cran --ignore-vignettes --no-examples --install-args=--build"

before_install:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}
  - cat DESCRIPTION
  - export PACKAGE_NAME=`package_name`
  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck

after_success:
  - cat ${RCHECK_DIR}/00install.out
  - cat ${RCHECK_DIR}/00check.log

after_failure:
  - cat ${RCHECK_DIR}/00install.out
  - cat ${RCHECK_DIR}/00check.log

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ];
    then
      PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
      PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ;
      mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ];
    then
      PKG_TARBALL=$(ls -1t *.tar.gz | head -n 1);
      PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'` ;
      mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ;
      echo "Built tarball is ${PKG_TARBALL_WITH_R}" ;
    fi
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]];
    then
      rm -f *.tar.gz;
    fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: mNg768mu+ZqwQbaj7d8sheCSuo7BDks8b1Gf4H1KNAcxO23pVgXvGjiVwx/AWWVSzGIA5mNuv2iaiMv9f9QLvFyOJsSaq/5N+97k/BY+TkY/VNoj8Z0ISjAb2qS6wnC7sJKxlo2TFjrMjy9qSpDuEnxM9Plg4Ey/6jLiUS2s2FEzvsMaBJnOEKcNTC5UJBRWmLKfeF/qqUP/rutL26VdNK4JsbpgJRdBb3Zt7s6Zrr2STLliDGz3tkdp7NKYBl+tmTtl61yOdYYBQZycvwbtSSs6GnPELLeSTpQMMDO76ecSB1pkGO6+Br7omXVEVt9wkUY0p7iNY7JrCQE8M2TCfrxlbjzwGGZr782AWr+IMUleB+msNKQHkgQPcKkJv6/H+9OelO0rRmvERPeGXlYTet2fBNDQZEk1aFg3QV1/r326VUGoBkz+p1Yx4E+4vHJspnMw8Vvr4vmWpEz/S2WwzkkWBHICO4q66SDN3OTlorIhCMQgufnx3RxiM4qhw1vUhBbmzv2ju6putVavNh3y60lohLJjN6OYitC2jZrb6LklfWoymsCZFXMUj6VrfOzB+qIRWxEbaPk3ocvfj4HjV3iHtdjMpDr4zhMDMMQC5nsKxbOny6Xdl4CVxSZBuktF2uNhWlIGeyA+llkiFotY8ILs1eW4kdHjSDYKe/tmntE=
  file_glob: true
  file: ${PACKAGE_NAME}*.t*gz
  on:
    repo: swarm-lab/${PACKAGE_NAME}
    tags: true
