language: R
sudo: false
cran: http://cran.rstudio.com
cache: packages
warnings_are_errors: false
os:
  - linux
  - osx

r_build_args: "--no-manual --no-build-vignettes"
r_check_args: "--as-cran --ignore-vignettes --no-examples --install-args=--build"

before_install:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}
  - cat DESCRIPTION
  - export PACKAGE_NAME=`package_name`
  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck

after_success:
  - cat ${RCHECK_DIR}/00install.out
  - cat ${RCHECK_DIR}/00check.log
  - |

       $(npm bin)/set-up-ssh --key "$encrypted_82d606cad81b_key" \
                             --iv "$encrypted_82d606cad81b_iv" \
                             --path-encrypted-key "github_deploy_key.enc"

after_failure:
  - cat ${RCHECK_DIR}/00install.out
  - cat ${RCHECK_DIR}/00check.log

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "DB8STUMdlC8l3gcycj2isY6oiQzxY+BwKHY9dnLdamF2ILJPg30k3iGV0SGgg9f8lDB9gye8hxlmHJAgi+2Tyz40pHz5qdf+Rtlu8Ax4JhIuWEn+EYHJ5BRaoq1P0cWLopKoVdCKsjhpgKCIfZNVSxodfq0e4d6OU0djkC5MIVnrZb2zp9eOElBVIagUrv11nVbhShK1RoO7orPxmt40jRv/hz5LQky0i9z2BfE5sHGAgWa0l7PMhOrKUgKMY8ia5/oEtmGJtIlTkp2UpkH2nHXV+zbEUuRnTbjzeTtbppDwvnPOx76q6pTNpr5lwxcuLUqjmntJJ3vWylMQr3hbo/lfsQ+QoMaXnJw+ypZxLjDgAeMGDvNkZ1SJrjtJESG7xO87vsfjC0cmwzsHy5F190I0dky1Oi8jWGCI7zXY8AHXXk3CXDQ1fAJCkDYLvBM9pCkeavXyXikHx3xucJ89Op0VA6nQDw7oifChTkh5QmcMb/rBqXPTGefeHX17ZUDtycHJEK7qXwnjpiQUESFWxNNfRQSlXHybSPQAdCI6BO7uTYXtZf+VSKr4P8eyWt/KtaB8wJVkKTRpqsR3ytR/JbzGBoRfSlufI7R0+9CXmNeY6TRstMvR5lcA8kpNYq4pGH6JrPZNaogySUWZ6GvZ/LxFqjrOn4yuWRv+39x2CQ8="
  file: "${PACKAGE_NAME}*.t*gz"
  file_glob: true
  on:
    repo: swarm-lab/${PACKAGE_NAME}

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -f *.tar.gz; fi
