# DO NOT CHANGE
init:
  ps: |
    $ErrorActionPreference = "Stop"
    Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
    Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary


# Adapt as necessary starting from here
environment:
  global:
    WARNINGS_ARE_ERRORS: 0.0
    USE_RTOOLS: yes
    R_CHECK_INSTALL_ARGS: --install-args=--build

  matrix:
  - R_VERSION: stable
    RTOOLS_VERSION: 34
    CRAN: http://cran.rstudio.com

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs
  - path: '*.Rcheck\**\*.out'
    name: Logs
  - path: '*.Rcheck\**\*.fail'
    name: Logs
  - path: '*.Rcheck\**\*.Rout'
    name: Logs
  - path: '\*_*.tar.gz'
    name: Bits
  - path: '\*_*.zip'
    name: Bits

deploy:
  provider: GitHub
  description: Windows Binary
  auth_token:
    secure: mNg768mu+ZqwQbaj7d8sheCSuo7BDks8b1Gf4H1KNAcxO23pVgXvGjiVwx/AWWVSzGIA5mNuv2iaiMv9f9QLvFyOJsSaq/5N+97k/BY+TkY/VNoj8Z0ISjAb2qS6wnC7sJKxlo2TFjrMjy9qSpDuEnxM9Plg4Ey/6jLiUS2s2FEzvsMaBJnOEKcNTC5UJBRWmLKfeF/qqUP/rutL26VdNK4JsbpgJRdBb3Zt7s6Zrr2STLliDGz3tkdp7NKYBl+tmTtl61yOdYYBQZycvwbtSSs6GnPELLeSTpQMMDO76ecSB1pkGO6+Br7omXVEVt9wkUY0p7iNY7JrCQE8M2TCfrxlbjzwGGZr782AWr+IMUleB+msNKQHkgQPcKkJv6/H+9OelO0rRmvERPeGXlYTet2fBNDQZEk1aFg3QV1/r326VUGoBkz+p1Yx4E+4vHJspnMw8Vvr4vmWpEz/S2WwzkkWBHICO4q66SDN3OTlorIhCMQgufnx3RxiM4qhw1vUhBbmzv2ju6putVavNh3y60lohLJjN6OYitC2jZrb6LklfWoymsCZFXMUj6VrfOzB+qIRWxEbaPk3ocvfj4HjV3iHtdjMpDr4zhMDMMQC5nsKxbOny6Xdl4CVxSZBuktF2uNhWlIGeyA+llkiFotY8ILs1eW4kdHjSDYKe/tmntE=
  draft: no
  prerelease: no
  on:
    APPVEYOR_REPO_TAG: true
